apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-staging
  namespace: argocd
  labels:
    app.kubernetes.io/instance: app-of-apps
spec:
  project: default
  source:
    repoURL: https://charts.releases.teleport.dev
    chart: teleport-cluster
    targetRevision: 17.0.1
    helm:
      values: |
        clusterName: teleport-staging
        auth:
        serviceAccountName: teleport-staging
          replicaCount: 1
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
        proxy:
          serviceAccountName: teleport-staging-proxy
          replicaCount: 1
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
