apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rbizzell40/argocd-playground.git
    targetRevision: main
    path: apps/teleport-cluster
    helm:
      valueFiles:
        - environments/staging/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true