# environments/staging/values.yaml
teleport-cluster:
  clusterName: "teleport-staging"
auth:
  replicaCount: 1
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
proxy:
  replicaCount: 1
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"