{{- if .Values.enabled }}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "teleport-cluster.operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teleport-cluster.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "teleport-cluster.operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "teleport-cluster.operator.serviceAccountName" . }}
{{- end }}
{{- end }}
